# Generated by Django 3.2.8 on 2021-11-16 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panelnumber',
            name='name',
            field=models.CharField(max_length=12),
        ),
        migrations.DeleteModel(
            name='Panels',
        ),
    ]
