# Generated by Django 3.2.8 on 2021-11-25 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0002_auto_20211116_2040'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('time', models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='paneldetail',
            name='interview_date',
        ),
        migrations.AddField(
            model_name='paneldetail',
            name='interview_slot',
            field=models.ManyToManyField(blank=True, to='panel.InterviewSlot'),
        ),
    ]
