# Generated by Django 3.2.8 on 2021-11-25 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0003_auto_20211125_1038'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interviewslot',
            old_name='date',
            new_name='slot',
        ),
        migrations.RemoveField(
            model_name='interviewslot',
            name='time',
        ),
    ]
